# Generated by Django 5.2.1 on 2025-06-09 07:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('description', models.TextField(verbose_name='Описание клиники')),
                ('mission', models.TextField(blank=True, verbose_name='Миссия клиники')),
                ('history', models.TextField(blank=True, verbose_name='История клиники')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(default='Без описания', max_length=500, verbose_name='Описание категории')),
                ('image', models.ImageField(default='categories/default.jpg', upload_to='categories/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='URL-имя')),
                ('description', models.TextField(default='Без описания', max_length=500, verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность (мин)')),
                ('image', models.ImageField(upload_to='service_image/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SheduleClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
            ],
            options={
                'verbose_name': 'Расписание клиники',
                'verbose_name_plural': 'Расписания клиник',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-имя')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinic_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание достижения')),
                ('year', models.PositiveIntegerField(verbose_name='Год достижения')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clinic_app.aboutclinic')),
            ],
            options={
                'verbose_name': 'Достижение клиники',
                'verbose_name_plural': 'Достижения клиники',
            },
        ),
        migrations.CreateModel(
            name='ReviewClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Удовлетворительно'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка от - 1 до 5')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус модерации')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic_app.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
