# Generated by Django 5.2.1 on 2025-05-29 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Удовлетворительно'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка от - 1 до 5')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус модерации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='URL-имя')),
                ('description', models.TextField(default='Без описания', max_length=500, verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('duration', models.PositiveSmallIntegerField(help_text='Продолжительность услуги в минутах', verbose_name='Длительность (мин)')),
                ('image', models.ImageField(upload_to='service_image/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Без описания', max_length=500, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/', verbose_name='Фото категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinic_app.category', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['rating'], name='clinic_app__rating_a89512_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='clinic_app__is_acti_541f91_idx'),
        ),
        migrations.AddField(
            model_name='reviewclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic_app.clinic', verbose_name='Клиника'),
        ),
    ]
