# Generated by Django 5.2.1 on 2025-06-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_app', '0001_initial'),
        ('doctors_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclinic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь кто оставил отзыв'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic_app.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors_app.doctor', verbose_name='Врачи'),
        ),
        migrations.AddField(
            model_name='sheduleclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='clinic_app.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='clinic_app.aboutclinic'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['rating'], name='clinic_app__rating_a89512_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='clinic_app__is_acti_541f91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewclinic',
            unique_together={('user', 'clinic')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('clinic', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='sheduleclinic',
            unique_together={('clinic', 'day_of_week')},
        ),
    ]
