# Generated by Django 5.2.1 on 2025-05-29 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_reviewclinic_service_alter_category_options_and_more'),
        ('doctors_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclinic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь кто оставил отзыв'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic_app.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='doctors_app.doctor', verbose_name='Врачи'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewclinic',
            unique_together={('user', 'clinic')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('clinic', 'slug')},
        ),
    ]
