# Generated by Django 5.2.1 on 2025-06-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('description', models.TextField(verbose_name='Описание клиники')),
                ('mission', models.TextField(blank=True, verbose_name='Миссия клиники')),
                ('history', models.TextField(blank=True, verbose_name='История клиники')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
        migrations.CreateModel(
            name='ClinicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание достижения')),
                ('year', models.PositiveIntegerField(verbose_name='Год достижения')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clinic_app.aboutclinic')),
            ],
            options={
                'verbose_name': 'Достижение клиники',
                'verbose_name_plural': 'Достижения клиники',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='clinic_app.aboutclinic')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SheduleClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='clinic_app.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Расписание клиники',
                'verbose_name_plural': 'Расписания клиник',
                'unique_together': {('clinic', 'day_of_week')},
            },
        ),
    ]
