# Generated by Django 5.2.1 on 2025-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_reviewclinic_user_service_clinic_service_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Длительность (мин)'),
        ),
    ]
