# Generated by Django 5.2.1 on 2025-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='nikname',
            field=models.CharField(default=None, verbose_name='Никнейм'),
        ),
    ]
