# Generated by Django 5.2.1 on 2025-05-30 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0003_remove_doctor_created_at_remove_doctor_updated_at'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctors_app.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания кода'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован ли код?'),
        ),
    ]
