# Generated by Django 5.2.1 on 2025-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_appointment_doctor_appointment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='something',
            name='doctor',
        ),
        migrations.RemoveIndex(
            model_name='smsverification',
            name='users_app_s_email_799db0_idx',
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['email', 'code'], name='users_app_s_email_8f668a_idx'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Something',
        ),
    ]
