# Generated by Django 5.2.1 on 2025-06-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_smsverification_nikname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsverification',
            old_name='nikname',
            new_name='name',
        ),
    ]
