# Generated by Django 5.2.1 on 2025-06-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_rename_nikname_smsverification_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsverification',
            old_name='name',
            new_name='user_name',
        ),
    ]
