# Generated by Django 5.2.1 on 2025-06-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_rename_name_smsverification_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsverification',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, verbose_name='Никнейм'),
        ),
    ]
