# Generated by Django 5.2.1 on 2025-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
