# Generated by Django 5.2.1 on 2025-05-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
    ]
