# Generated by Django 5.2.1 on 2025-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0003_remove_doctor_created_at_remove_doctor_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Опыт работы'),
        ),
    ]
